apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finance-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/valvarezo/dotnet-cloud-stack.git
    targetRevision: HEAD
    path: argocd/apps
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
